# Database implementation
database:
  # for multi-server networks, use "MONGO"
  # for single-server, use "JSON" (aka flat-file)
  implementation: "JSON"
  options:
    host: "127.0.0.1"
    port: 27017
    dbName: "two-factor-auth"
    authentication:
      enabled: false
      username: "admin"
      password: ""
settings:
  # The name that appears in the 2FA app
  issuer-name: "EvilBlock"
  # If only players with the '2fa.access' permission are allowed to setup 2FA
  require-permission: true
  # If players with the '2fa.access' permission are required to setup 2FA if they haven't already
  require-setup: true
  # The commands that players are allowed to execute while not verified
  whitelisted-commands:
    - "auth"
    - "2fasetup"
    - "setup2fa"
  # The text the player must enter to agree to the setup terms
  agree-text: "yes"
  # If the bypass command can only be executed by the console
  bypass-command-op-only: true
  # If players with the `2fa.bypass` permission are granted identity verification bypass
  use-bypass-permission: false
  # If damage to players in the locked state is disabled
  disable-damage-to-locked-players: false